#!/bin/bash
# Genomics Git Organization Startup Script

# Display organization info
echo "🚀 GENOMICS GIT ORGANIZATION PROJECT"
echo "=================================="
echo ""
echo "The Git organization project for genomics repositories has been organized."
echo "Files are now stored in a structured directory at:"
echo "  /home/sdodl001/genomics-git-organization/"
echo ""
echo "📊 Current Status:"
echo "  ✅ All 5 repositories deployed to GitHub"
echo "  ✅ Remotes configured for all 3 accounts"
echo "  ✅ v0.1.0 tags created for all repositories"
echo "  ✅ Project organization complete"
echo ""
echo "🔧 Utility Tools Available:"
echo "  📁 gitorg    - Navigate the project structure"
echo "  📦 repoutil  - Manage repository operations"
echo ""
echo "📚 Documentation:"
echo "  📄 STATUS.md           - Current deployment status"
echo "  📄 NEXT_STEPS.md       - Implementation plan for monitoring"
echo "  📄 GITORG_REFERENCE.md - Quick reference for gitorg commands"
echo ""
echo "Try these commands:"
echo "  ./gitorg help     - Show gitorg commands"
echo "  ./repoutil help   - Show repository management commands"
echo "  ./gitorg summary  - Show organization summary"
echo ""
